### ISSUE TITLE
Not loading library

### ISSUE THREAD

**Issue by tytower** [sparkfun/BMP180_Breakout#7]
I think you should include a note for anyone downloading the zip file that  you must go to the Library/Arduino directory and only copy the 6 files there (examples etc )to leave under SFE_BMP180 otherwise its a ballsup with all the other stuff you have in there!

**Comment by mgrusin** [comment]
Sorry for the confusion. We've tried to make this clear in our step-by-step tutorials, but because of the way Github works you can only download everything at once. To solve this we are currently splitting all of our product repositories into separate hardware and Arduino libraries, so this should be easier in the future. (In fact, you should soon be able to add libraries from within the Arduino IDE!) Thanks for the feedback!

**Comment by tytower** [comment]
Thanks Mike . Thats a good system it seems especially as it updates each time you open the IDE

While I have you there...There is an issue with the BMP180 library that needs repairing . I sent you another email to technical but have had no response here is the link
https://github.com/sparkfun/BMP180_Breakout/issues/1#issuecomment-106976786

I repaired my library and it definately seems to have fixed my issue .
Cheers from the Great Barrier Reef
--------------------------------------------------------------------------On Mon, 01 Jun 2015 10:22:03 -0700
Mike Grusin <notifications@github.com> wrote:

> Sorry for the confusion. We've tried to make this clear in our step-by-step tutorials, but because of the way Github works you can only download everything at once. To solve this we are currently splitting all of our product repositories into separate hardware and Arduino libraries, so this should be easier in the future. (In fact, you should soon be able to add libraries from within the Arduino IDE!) Thanks for the feedback!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sparkfun/BMP180_Breakout/issues/7#issuecomment-107644708


-- 
Yahoo <tytower@yahoo.com>

**Comment by ToniCorinne** [comment]
Because of the new Arduino IDE requirements, we've also split all of our libraries into their own repositories, which negates the .zip issue.  You can find the library [here](https://github.com/sparkfun/BMP180_Breakout_Arduino_Library). The libraries are synced with the product repos using git subtree commands.
